### PR TITLE
Allow for symfony/console v2 or v3

### LINKED ISSUE #30: Update symfony/console
Please update symfony console dependency:
"symfony/console": "^2.1|^3.0",

### PR DESCRIPTION
**Pull request by keradus**
Closes #30

### CODE REVIEW

**Comment by clue** [comment]
Thanks! Can you amend your commit to also include the updated `composer.lock` file? See also Travis' build output:

> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

https://travis-ci.org/clue/graph-composer/jobs/113653893#L146

**Comment by keradus** [comment]
Sadly, I could not. That's why I didn't send PR in first place.
I could only contribute from website today.

Please feel free to do it on your side.

**Comment by clue** [comment]
Closing this because it's currently incomplete. I'm happy to get this in once anybody files a complete PR :+1:

**Comment by skobkin** [comment]
@clue, When some stable release with Symfony Console 3/4 will be released? Now it's only possible to install using `dev-master`.

```
$ composer g require clue/graph-composer
Changed current directory to /home/skobkin/.composer
Using version ^1.0 for clue/graph-composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for clue/graph-composer ^1.0 -> satisfiable by clue/graph-composer[v1.0.0].
    - Conclusion: remove symfony/console v3.2.13
    - Conclusion: don't install symfony/console v3.2.13
    - clue/graph-composer v1.0.0 requires symfony/console ~2.1 ...
```

All PHP tools that I have installed already using `~3.0 || ~4.0` console component support.

**Comment by clue** [comment]
Thanks for your interest, I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and you want a quote, please check out my profile and send me an email)*

**Comment by keradus** [comment]
a PR for... new release? men, just tag it and that's it.
you don't need any company supporting you with cash for writing `git tag ...` ;)

**Comment by clue** [comment]
The latest tagged release does indeed support only `"symfony/console": "~2.1"` while the latest master supports `"symfony/console": "^2.1 || ^3.0"`. If this is an issue in your use case, I would suggest using `dev-master` until the next release is tagged.

Thank you for your input, I'll consider getting a new release out as soon as time permits.  If you feel anything is missing here, I'm happy to accept PRs :+1:

**Comment by keradus** [comment]
That's exactly what @skobkin said. as there is no new release, he is forced to rely on `dev-master` thus asking for release...

**Pull request closed without merging**
