### PR TITLE
Add options to exclude packages and dependencies from graph.

### PR DESCRIPTION
**Pull request by markuspoerschke**
Dev dependencies of dependencies are not shown anymore, because they are not relevant for the current package.

* `--no-dev` will hide dev dependencies
* `--no-php` will hide the constraints regarding the PHP version
* `--no-ext` will hide PHP extensions
* `--depth` will limit the depth of the generated graph
* `--exclude-regex` allows to apply regular expressions to hide packages
* `--only-regex` show only packages with their name matching the expression
* `--exclude-type` exclude pacakges with given type
* `--only-type` only show packages of given type

The filters are never applied to the root packge.

To apply these filters the packages must be rendered in the correct order. Before the packages were drawn "randomly" and were connected later on. Now packages are drawn from root package and only if they are a dependency of a package. This allow filtering for dependencies and packages. If a package (node) is missing, then the dependency (edge) is not shown. Vice versa the dependency (edge) is not shown when the package (node) is not available.

**New**
output_exfsyf

**Old**
output_n3qgvf

## Open TODOs:

* [x] Update documentation (add examples etc.)
* [x] Fix PHPUnit tests (they are surprisingly still working ;-))
* [x] Cleanup code / code style etc.
* [x] Update CHANGELOG
* [x] Visualize rendering process so that new algo to render graph is understood (compare old vs. new)

### CODE REVIEW

**Comment by markuspoerschke** [comment]
@clue Can you have a look on this one? The changes are huge, because the complete graph generation needed to be changed to support filtering by depth and filtering by packages.

I guess there are more filters needed like: `--exclude-dependencies-from` to exclude dependencies from sub packages or so. But this could be added even later :)

**Comment by machour** [comment]
PR tested on a heavy set of packages, and working like a charm, thank you @markuspoerschke

**Comment by samdark** [comment]
We'd love to use what @wol-soft created. @clue?

**Comment by floriankraemer** [comment]
Can anyone merge this, please? :)

**Comment by markuspoerschke** [comment]
@clue ?

**Comment by patricknelson** [comment]
Bump. This would be amazing to see! My first time using `graph-composer` resulted in such a massive dependency tree that it practically rendered itself useless (since it was almost too complex to visually parse intuitively). The graph was so wide that you end up getting lost in the weaving lines.

**Comment by clue** [comment]
@markuspoerschke Thank you very much for looking into this and filing this PR! :+1: 

This PR contains a lot of nice features that I would love to see as part of graph-composer in the future! Unfortunately, it adds a fair amount of complexity and does not currently contain any tests, so it's a bit hard to review.

I'm currently in the process of updating this project and will work on the test suite next. The plan is to create a better base to build on top of, perhaps we can then rebase (part of) this PR to take advantage of this.

As a first step, I'm currently looking into `--dev` and `--no-dev` flags as per #2. Let's continue the discussion in #2 first and then afterwards look into how we can get this PR here ready! :shipit: 

---

@wol-soft Really nice, would indeed love to see an `--outdated` flag in the future! Let's continue this discussion in #65! :shipit:

**Pull request closed without merging**
